### ISSUE TITLE
ERROR On install extension on Blender 4.1

### ISSUE THREAD

**Issue by jovanygonzalez** [takahirox/glTF-Blender-IO-materials-variants#21]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Jovan\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\glTF-Blender-IO-materials-variants-0_0_3\__init__.py", line 2, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_materials
ImportError: cannot import name 'gltf2_blender_gather_materials' from 'io_scene_gltf2.blender.exp' (unknown location)

**Comment by Log-Mushun** [comment]
Hi, this plugin is no longer necessary, as you can now activate the material variants option using the Import-Export glTF 2.0 format addon. For a more detailed guide, you can refer to this documentation:  https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html
